### ISSUE TITLE
Taint functionality missing with update command enabled

### ISSUE THREAD

**Issue by adudek** [scottwinkler/terraform-provider-shell#14]
Hello,
thank You for your awesome work! This basically is what Terraform should have been from the beginning (pluggable shell scripts with state).

Reason for this feature, is to make shell reasource "experience" more "null_resource like". Currently the only way to taint shell resource (I know of) is to include trigger env value in lifecycle_commands section.
example: delete = "bash -eu scripts/delete.sh; #${var.tainted}'"

How I would envision resource tainting is by:
- "triggers" variable (null_resource style), this also enables use case where resource can be tainted based on external input, without exposing values to shell environment
- separate tainted_environment block (basically the same as environment but change in one of those values forces resource recreation even with update command present)

Sidequestion:
any plans on hitting official plugin status?

Applause for excellent work!

**Comment by scottwinkler** [comment]
@adudek for me, this was an obvious plugin and I don't know why nobody else created it sooner. I like the idea about resource tainting. Oftentimes when I am using this resource I get into a bad state and have to manually delete it from the state file. Having a way to taint the resource through some trigger could certainly make the development process easier. I don't understand your suggestion for a tainted_environment block, but a triggers map could certainly work. I'll make this an action item, but I probably won't get around to it for at least a few weeks.

At HashiConf, the Terraform team said that there would be a provider registry announced within the next few months. I intend to register this plugin there, and do whatever it takes to get the "green light" status, like they have in the module registry. As it is right now, HashiCorp is not interested in owning any of the community providers, they only care about partnerships with major cloud vendors.

**Comment by adudek** [comment]
That's excellent news! Keep it up!
I advertise this plugin to whomever wants to hear about it. Its a keeper :+1:

**Comment by scottwinkler** [comment]
@adudek I have created a pull request to add the triggers functionality. Please review and if you are happy with it then I will merge and close this issue.

**Comment by adudek** [comment]
Ready to merge!

**Comment by scottwinkler** [comment]
merged so closing ticket
