### ISSUE TITLE
Feature request: add support for complex JSON structures

### ISSUE THREAD

**Issue by bentterp** [scottwinkler/terraform-provider-shell#31]
I think it would be highly useful if the JSON structures could be more complex, ie contain nested maps and lists.

A real world example:
`az provider list --subscription ######################### | jq '.[]|select(.namespace == "Microsoft.RedHatOpenShift")'`
Output looks like this:
```
{
  "authorizations": [
    {
      "applicationId": "#########################",
      "managedByAuthorization": {
        "allowManagedByInheritance": true
      },
      "managedByRoleDefinitionId": "########################",
      "roleDefinitionId": "###########################"
    }
  ],
  "id": "/subscriptions/####################/providers/Microsoft.RedHatOpenShift",
  "namespace": "Microsoft.RedHatOpenShift",
  "registrationPolicy": "RegistrationRequired",
  "registrationState": "Registered",
  "resourceTypes": [
    {
      "aliases": null,
      "apiVersions": [
        "2019-12-31-preview"
      ],
      "capabilities": "None",
      "locations": [],
      "properties": null,
      "resourceType": "operations"
    }
  ]
}
```

I t would probably be a huge amount of work to implement parsing of that structure..... but I don't think you need to as Hashicorp has already done that:
https://www.terraform.io/docs/configuration/functions/jsondecode.html

Running that function on the output above ( `output "json_namespace" { value = jsondecode(file("./scripts/namespace.json")) }` ) results in this variable
```
json_namespace = {
  "authorizations" = [
    {
      "applicationId" = "##########################"
      "managedByAuthorization" = {
        "allowManagedByInheritance" = true
      }
      "managedByRoleDefinitionId" = "##############################"
      "roleDefinitionId" = "################################"
    },
  ]
  "id" = "/###################################/providers/Microsoft.RedHatOpenShift"
  "namespace" = "Microsoft.RedHatOpenShift"
  "registrationPolicy" = "RegistrationRequired"
  "registrationState" = "Registered"
  "resourceTypes" = [
    {
      "apiVersions" = [
        "2019-12-31-preview",
      ]
      "capabilities" = "None"
      "locations" = []
      "resourceType" = "operations"
    },
  ]
}
```
 which can then be used like any other map structure in the rest of the code.

**Comment by scottwinkler** [comment]
This is a great idea. I will see about implementing this

**Comment by scottwinkler** [comment]
@bentterp I added support for complex nested JSON. Let me know what you think. If you like it then I will close this ticket.I still would like to consider a way to use custom nodes to access complex data, but I will just open a new ticket for that

**Comment by scottwinkler** [comment]
Closing this ticket since the feature was added to the latest release. I opened a new ticket to add support for traversing complex JSON based on what I suggested here

**Comment by bentterp** [comment]
@scottwinkler  Great work, thanks.

I've been doing some testing here and it works in some cases, like if the output is a map, then I can pick attributes from the map. Lists seems to be a problem, but I'm not sure if that's due to Azure CLI or the parsing in the provider.
IF I manage to create a good test for this and it fails, I'll open a new ticket.
