### ISSUE TITLE
Errors from `delete` command are swallowed

### ISSUE THREAD

**Issue by jcarlson** [scottwinkler/terraform-provider-shell#40]
I'm using this provider to wrap AWS API commands for resources that Terraform does not yet support natively in the AWS provider.

On destroy, my `delete` command threw an error, but the shell script provider swallowed it and marked the resource as destroyed.

It would appear that, unlike the create, read and update operations, [delete does not check the exit code](https://github.com/scottwinkler/terraform-provider-shell/blob/master/shell/resource_shell_script.go#L245) of the script.

IMHO, the delete operation should check the exit code and fail destruction of the resource if the script did not exit cleanly.

**Comment by scottwinkler** [comment]
okay that sounds like a good idea. In the meantime can you set TF_LOG to debug? At least that way you can still get logs for delete operation
