### ISSUE TITLE
Thanks - this is awesome!

### ISSUE THREAD

**Issue by lawrencegripper** [scottwinkler/terraform-provider-shell#52]
Just wanted to say a really big thank you for the work on the provider it's been super useful, been using it to [create a basic databricks tf provider](https://github.com/lawrencegripper/hack-databricksterraform/).

**Comment by lawrencegripper** [comment]
Closing as not really an issue but couldn't see another way to say thanks.

**Comment by scottwinkler** [comment]
Thanks! And great job with the databricks provider, that's awesome 👍
