### ISSUE TITLE
Add to terraform provider registry

### ISSUE THREAD

**Issue by scottwinkler** [scottwinkler/terraform-provider-shell#57]
Now that there is an official provider registry, this provider should be added

**Comment by Zordrak** [comment]
Going out of my mind trying to convert an existing project that uses this plugin as a local file from 0.12 to 0.13. Big thumbs up for pre-compiling and putting on the remote registry.

**Comment by pacon-vib** [comment]
I initially got a bit confused reading the Terraform 0.13 documentation. I got the shell provider working by `curl`ing it off GitHub, unzipping it and putting it under `.terraform/plugins/registry.terraform.io/hashicorp/shell/1.7.0/linux_amd64/`. So Terraform labels it "hashicorp/shell", but it works, and that's the main thing, right?

@scottwinkler I'm currently using your provider on a project to wrap some PowerShell scripts. If I can be of any assistance in getting the provider into the registry please let me know. 

As I understand it the requirements are:
- [x] the release zips file and binaries have to be named according to the convention (I believe you already do this)
- [ ] the release needs to contain a `terraform-provider-{NAME}_{VERSION}_SHA256SUMS` containing checksums for the zip files
- [ ] the release needs to contain a `terraform-provider-{NAME}_{VERSION}_SHA256SUMS.sig` containing a signature for the checksums file
- [ ] create a Terraform Registry account
- [ ] associate your GPG key with your Terraform Registry account: https://registry.terraform.io/settings/gpg-keys
- [ ] then publish the provider: https://registry.terraform.io/publish/provider to publish the provider

I think this is a one-off job, and then the Registry automatically gets notified via webhook when you put out new releases.

The instructions are here: https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by scottwinkler** [comment]
it is now on the provider registry but you need Terraform 0.13 to get it. here is a sample configuration:
link: https://registry.terraform.io/providers/scottwinkler/shell

```
terraform {
  required_providers {
    shell = {
      source = "scottwinkler/shell"
      version = "1.7.1"
    }
  }
}

data "shell_script" "weather" {
  lifecycle_commands {
    read = <<-EOF
        echo "{\"SanFrancisco\": \"$(curl wttr.in/SanFrancisco?format="%l:+%c+%t")\"}"
    EOF
  }
}
```

**Comment by pacon-vib** [comment]
I cannot thank you enough Scott. This is gonna be awesome.

**Comment by Zordrak** [comment]
Big thanks! I can finally dump the binary from my repo and all the ugly custom provider management!
