### ISSUE TITLE
Ignore diff on lifecycle_commands

### ISSUE THREAD

**Issue by scottwinkler** [scottwinkler/terraform-provider-shell#69]
Even though ForceNew has been removed it still doesnt help because it will use old read command. Put something in to ignore diffs for this attribute

**Comment by rucciva** [comment]
hi @scottwinkler , i've made a similar resource inspired from yours, and [made some modifications](https://registry.terraform.io/providers/TelkomIndonesia/linux/latest/docs/resources/script?pollNotifications=true#updating-resource) that might relate to this issue. Are you accepting pull  request for this? i could submit one if so and also solve #77 #78

**Comment by scottwinkler** [comment]
Hello rucciva. Yes I am accepting pull requests. I would be happy to have your contribution.
