### ISSUE TITLE
Support automatic provider installations in Terraform 0.13

### ISSUE THREAD

**Issue by jcarlson** [scottwinkler/terraform-provider-shell#70]
Terraform 0.13 has been released and provides a mechanism for automatically installing third-party providers.

Automatic installation would be a great addition to this provider.

https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13/

**Comment by scottwinkler** [comment]
You can already do this since I published it on the provider registry. I added a snippet to the documentation to be more clear.

https://github.com/scottwinkler/terraform-provider-shell/blob/master/README.md#using-the-provider

add this to your TF config:
```
terraform {
  required_providers {
    shell = {
      source = "scottwinkler/shell"
      version = "1.7.3"
    }
  }
}
```

**Comment by jcarlson** [comment]
Did not know that. Thank you for clarifying, and keep up the good work!
