### ISSUE TITLE
Documentation should stipulate terraform 0.13 or above

### ISSUE THREAD

**Issue by gtmtech** [scottwinkler/terraform-provider-shell#71]
You specify 0.12 or above in the README, but your provider declaration uses new terraform 0.13 syntax, so it would be good if the requirements could match or it would be made clear what the terraform 0.12 syntax is. 

As it stands I followed the README exactly command for command, and couldnt get the provider recognised with terraform 0.12 - with terraform 0.13 it was fine

**Comment by dr4Ke** [comment]
I'm using it with terraform 0.12.29 for the moment. I'm downloading the provider binary manually in the current directory or in `.terraform/plugins/linux_amd64`. Then use it with:

``` hcl
provider "shell" {
    interpreter = ["/bin/sh", "-c"]
    enable_parallelism = false
}
```

And no `terraform/required_providers` definition block.

**Comment by scottwinkler** [comment]
@dr4Ke is right, if you build this provider yourself then you can use this for Terraform 0.12. But it is also published in the provider registry so it works for Terraform 0.13 and above also. Just know that I will not be supporting 0.12 compatibility going forward, and future versions may not be backwards compatible.
