### ISSUE TITLE
Force replacement environment variable

### ISSUE THREAD

**Issue by scottwinkler** [scottwinkler/terraform-provider-shell#72]
@scottwinkler I've just noticed that this now causes my resources to force replacement whenever the environment variables change. Is this intended? FYI - @pacon-vib

**Comment by jwicks** [comment]
@scottwinkler thanks for this. Could we get a new release with the fix?

**Comment by scottwinkler** [comment]
@jwicks 1.7.4 is now out. Sorry it took so long, I just automated the release pipeline so getting new releases out there won't be a problem from now on
