### ISSUE TITLE
previous and new output swapped

### ISSUE THREAD

**Issue by dr4Ke** [scottwinkler/terraform-provider-shell#76]
In the debug log, the previous output and new output are swapped. This was puzzling me since the new output didn't equal the read output script.

https://github.com/scottwinkler/terraform-provider-shell/blob/04e86df9675146607e0de5deaac1a62cd6884f11/shell/resource_shell_script.go#L199

**Comment by scottwinkler** [comment]
thank you for this, i will fix in the next version.
